# Generated by Django 3.0 on 2022-06-19 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='date when the object was created', verbose_name='creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='date when the object was modified', verbose_name='update date')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='Last name')),
                ('note', models.FloatField(default=0, max_length=100, verbose_name='Note')),
                ('created_by', models.ForeignKey(blank=True, help_text='user who created the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creation user')),
                ('modified_by', models.ForeignKey(blank=True, help_text='user who performed the update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='update user')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
